### ISSUE TITLE
Audio Checklist

### ISSUE THREAD

**Issue by KaiserLeo7** [KaiserLeo7/QuickSands#175]
**User Story**
User wants to hear the differenc between every area in the game and each hero/enemy attacks.

**Description**
Audio needs to be added to all areas of the game.

**Acceptance Criteria**
  **Scenes - Background Sound**
  - [x] Blacksmith
  - [x] Inn
  - [x] Main Menu
  - [x] Town Scene
  - [x] Quest Board - Same as Town Scene
  - [x] Trade Shop - Same as Town Scene
  - [x] Ship Shop
  - [x] Travel
  
  **Heroes**
  Mage
  - [x] Basic Attack
  - [x] Special Attack
  
  Warrior
  - [x] Basic Attack
  - [x] Special Attack
  
  Ranger
  - [x] Basic Attack
  - [x] Special Attack
  
  Spearman
  - [x] Basic Attack
  - [x] Special Attack
  
  Spellcaster
  - [x] Basic Attack
  - [x] Special Attack
  
  **Monsters - Searing Rock**
  Zombie
  - [x] Basic Attack
  
  Asmodeus
  - [x] Basic Attack
  
  Fire Golem
  - [x] Basic Attack
 
  **Monsters - Wyrms Peak**
  DeathDrone
  - [x] Basic Attack
  
  Leviathan
  - [x] Basic Attack
  
  Dragon
  - [x] Basic Attack
  - [x] Special Attack
  
  **Monsters - Infernal Maw**
  Mammon
  - [x] Basic Attack
  
  Belphegor
  
  - [x] Basic Attack
  
  Satan
  - [x] Basic Attack
  - [x] Special Attack
  
  **Button - Special Sounds**
  - [x] ShipShop Vehicle Purchase
  - [x] BlackSmith Upgrade
  - [x] Inn Hero Hired
  - [x] Trade Good Bought/Sold
  - [x] QuestBoard Accept Quest
  - [x] QuestBoard Abandon Quest
  - [x] QuestBoard Complete Quest
  - [x] Generic Button Click
  - [x] Map Open
  - [x] Map Go Sound
  - [x] InvManager Hero Fired
  - [x] Travel Battle Won
  - [x] Travel Battle Lost
  - [x] Take Loot (Treasure & Battle)

**Testing**

- Go into every scene
- Fight every enemy
- Make sure everything has audio
